import type { WorldConfig } from "./WorldBuilder";

/* ═══════════════════════════════════════════
   50 WORLD CONFIGS — each with unique terrain,
   structures, particles, and atmosphere
   ═══════════════════════════════════════════ */

export const WORLD_CONFIGS: Record<string, WorldConfig> = {

/* ═══ MERCURY (5) ═══ */
  "mercury-surface": {
    name: "Mercury Surface Base", seed: 101,
    terrain: { type: "rocky", roughness: 1.2 },
    atmosphere: { color: "rgba(200,180,160,0.02)", opacity: 0.02, radius: 6 },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#b0a090", glowColor: "#ff8844" } },
      { type: "SolarArray", position: [2, 0, 1.5], params: { panels: 12, span: 1.2 } },
      { type: "SolarArray", position: [-2, 0, -1.5], params: { panels: 12, span: 1.2 } },
      { type: "AntennaTower", position: [0.5, 0, 2.5], params: { height: 0.5, color: "#ff8844" } },
      { type: "LandingPad", position: [3, 0, -2] },
      { type: "PowerCore", position: [-1.5, 0, 2], params: { color: "#ff6600" } },
      { type: "Airlock", position: [0.8, 0, -1.5] },
    ],
    particles: [{ type: "DustStorm", params: { color: "#8a7a68", count: 300, radius: 6 } }],
    lighting: { ambient: "#886644", ambientIntensity: 0.25, sunColor: "#ffaa44", sunIntensity: 0.8, sunPosition: [20, 15, 0] },
  },
  "mercury-observatory": {
    name: "Solar Observatory", seed: 102,
    terrain: { type: "rocky", roughness: 0.8 },
    structures: [
      { type: "ObservationTower", position: [0, 0, 0], params: { height: 0.6, color: "#ffaa44" } },
      { type: "TelescopeArray", position: [0, 0, 0], params: { scale: 0.8, color: "#ffaa44" } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#ffaa44" } },
      { type: "PowerCore", position: [-1.5, 0, -1.5], params: { color: "#ff8800" } },
      { type: "AntennaTower", position: [2, 0, -1], params: { color: "#ffaa44" } },
    ],
    particles: [],
    lighting: { ambient: "#886644", ambientIntensity: 0.2, sunColor: "#ffcc44", sunIntensity: 0.9, sunPosition: [25, 10, 0] },
  },
  "mercury-dark-side": {
    name: "Dark Side Cryo Lab", seed: 103,
    terrain: { type: "rocky", roughness: 0.6 },
    structures: [
      { type: "CryoTank", position: [0, 0, 0], params: { scale: 1.2, color: "#4488ff" } },
      { type: "CryoTank", position: [1.2, 0, 0.8], params: { color: "#4488ff" } },
      { type: "CryoTank", position: [-1.2, 0, -0.8], params: { color: "#4488ff" } },
      { type: "ResearchModule", position: [0, 0, 1.8], params: { color: "#4488ff" } },
      { type: "PowerCore", position: [0, 0, -1.8], params: { color: "#0066ff" } },
      { type: "Airlock", position: [1.5, 0, -1.5] },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#88ddff", count: 200, radius: 4 } }],
    lighting: { ambient: "#223344", ambientIntensity: 0.1, sunColor: "#4488ff", sunIntensity: 0.2 },
  },
  "mercury-caloris": {
    name: "Caloris Basin Research", seed: 104,
    terrain: { type: "rocky", roughness: 1.5 },
    structures: [
      { type: "DrillRig", position: [0, 0, 0], params: { scale: 1.2 } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#ff6644" } },
      { type: "AntennaTower", position: [-1.5, 0, -1.5], params: { color: "#ff6644" } },
      { type: "CargoContainer", position: [2, 0, 0], params: { color: "#ff8844" } },
    ],
    particles: [{ type: "DustStorm", params: { color: "#6a5a48", count: 400, radius: 7 } }],
    lighting: { ambient: "#664422", ambientIntensity: 0.3, sunColor: "#ff8844", sunIntensity: 0.7 },
  },
  "mercury-solar-sail": {
    name: "Solar Sail Launch Array", seed: 105,
    terrain: { type: "rocky", roughness: 0.5 },
    structures: [
      { type: "LaunchPad", position: [0, 0, 0], params: { scale: 1.5 } },
      { type: "SolarArray", position: [2.5, 0, 0], params: { panels: 16, span: 1.5, color: "#ffcc00" } },
      { type: "SolarArray", position: [-2.5, 0, 0], params: { panels: 16, span: 1.5, color: "#ffcc00" } },
      { type: "ObservationTower", position: [0, 0, 2.5], params: { color: "#ffcc00" } },
      { type: "FuelDepot", position: [2, 0, -2] },
      { type: "CommunicationArray", position: [-2, 0, 2] },
    ],
    particles: [],
    lighting: { ambient: "#886633", ambientIntensity: 0.3, sunColor: "#ffdd44", sunIntensity: 1, sunPosition: [30, 5, 0] },
  },

/* ═══ VENUS (5) ═══ */
  "venus-cloud-city": {
    name: "Cloud City Hub", seed: 201,
    terrain: { type: "gaseous", roughness: 0 },
    atmosphere: { color: "#e8c878", opacity: 0.15, radius: 8 },
    structures: [
      { type: "HabRing", position: [0, 0, 0], params: { radius: 0.5, scale: 1.5 } },
      { type: "SuspensionBridge", position: [1.2, 0, 0], params: { span: 0.8 } },
      { type: "SuspensionBridge", position: [-1.2, 0, 0], params: { span: 0.8 } },
      { type: "ResearchModule", position: [2, 0, 0.5], params: { color: "#ff8844" } },
      { type: "ResearchModule", position: [-2, 0, -0.5], params: { color: "#ff8844" } },
      { type: "AntennaTower", position: [0, 0, 2], params: { color: "#ffaa33" } },
      { type: "LandingPad", position: [0, 0, -2] },
      { type: "PowerCore", position: [0, 0, 0], params: { color: "#ff8800" } },
    ],
    particles: [{ type: "AcidRain", params: { color: "#88aa44", count: 400, width: 8 } }],
    lighting: { ambient: "#886644", ambientIntensity: 0.4, sunColor: "#ffaa33", sunIntensity: 0.3 },
  },
  "venus-sulfur-plant": {
    name: "Sulfur Processing Plant", seed: 202,
    terrain: { type: "gaseous", roughness: 0 },
    atmosphere: { color: "#ccaa44", opacity: 0.12, radius: 7 },
    structures: [
      { type: "Refinery", position: [0, 0, 0], params: { scale: 1.5 } },
      { type: "Refinery", position: [1.5, 0, 1.5], params: { scale: 1.2 } },
      { type: "FuelDepot", position: [0, 0, -2], params: { scale: 1.2 } },
      { type: "MiningConveyor", position: [0.5, 0, 0.5], params: { length: 0.6 } },
      { type: "CargoContainer", position: [-2, 0, 0], params: { color: "#ffaa33" } },
      { type: "Airlock", position: [2, 0, 0], params: { color: "#ffaa33" } },
    ],
    particles: [{ type: "AcidRain", params: { color: "#aa8844", count: 300, width: 7 } }],
    lighting: { ambient: "#664422", ambientIntensity: 0.3, sunColor: "#ffaa33", sunIntensity: 0.3 },
  },
  "venus-float-lab": {
    name: "Floating Research Lab", seed: 203,
    terrain: { type: "gaseous", roughness: 0 },
    atmosphere: { color: "#99ccdd", opacity: 0.1, radius: 7 },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#4488ff" } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#4488ff" } },
      { type: "ResearchModule", position: [-1.5, 0, -1.5], params: { color: "#4488ff" } },
      { type: "TelescopeArray", position: [0, 0, 0], params: { color: "#4488ff" } },
      { type: "SuspensionBridge", position: [0.8, 0, 0.8], params: { span: 0.6 } },
      { type: "AntennaTower", position: [2, 0, 0], params: { color: "#4488ff" } },
    ],
    particles: [{ type: "AcidRain", params: { color: "#88aadd", count: 200, width: 6 } }],
    lighting: { ambient: "#446688", ambientIntensity: 0.3, sunColor: "#88aaff", sunIntensity: 0.3 },
  },
  "venus-surface-probe": {
    name: "Surface Probe Station", seed: 204,
    terrain: { type: "rocky", roughness: 1.0 },
    atmosphere: { color: "#aa6633", opacity: 0.08, radius: 6 },
    structures: [
      { type: "LandingPad", position: [0, 0, 0] },
      { type: "AntennaTower", position: [1.5, 0, 1.5], params: { color: "#ff4422" } },
      { type: "ResearchModule", position: [-1.5, 0, -1.5], params: { color: "#ff4422" } },
      { type: "PowerCore", position: [0, 0, -2], params: { color: "#ff4400" } },
    ],
    particles: [{ type: "AcidRain", params: { color: "#886633", count: 500, width: 8 } }],
    lighting: { ambient: "#442211", ambientIntensity: 0.2, sunColor: "#ff6644", sunIntensity: 0.3 },
  },
  "venus-atmo-mine": {
    name: "Atmospheric Mining Rig", seed: 205,
    terrain: { type: "gaseous", roughness: 0 },
    atmosphere: { color: "#ddaa55", opacity: 0.15, radius: 8 },
    structures: [
      { type: "Refinery", position: [0, 0, 0], params: { scale: 2 } },
      { type: "FuelDepot", position: [2, 0, 0], params: { scale: 1.5 } },
      { type: "FuelDepot", position: [-2, 0, 0], params: { scale: 1.5 } },
      { type: "MiningConveyor", position: [1, 0, 1], params: { length: 0.8 } },
      { type: "MiningConveyor", position: [-1, 0, -1], params: { length: 0.8 } },
      { type: "LandingPad", position: [0, 0, -2.5] },
      { type: "HabitatDome", position: [0, 0, 2.5], params: { color: "#ddaa55", glowColor: "#ffcc33" } },
    ],
    particles: [{ type: "AcidRain", params: { color: "#aa8844", count: 500, width: 10 } }],
    lighting: { ambient: "#664422", ambientIntensity: 0.3, sunColor: "#ffcc33", sunIntensity: 0.3 },
  },

/* ═══ EARTH (5 procedural) ═══ */
  "earth-deep-sea": {
    name: "Deep Sea Research", seed: 301,
    terrain: { type: "oceanic", roughness: 0.2 },
    atmosphere: { color: "#224466", opacity: 0.12, radius: 7 },
    water: { surface: true },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#44aaff" } },
      { type: "ResearchModule", position: [2, 0, 0], params: { color: "#44aaff" } },
      { type: "Airlock", position: [1, 0, 1.5], params: { color: "#44aaff" } },
      { type: "PowerCore", position: [-1.5, 0, -1.5], params: { color: "#0066ff" } },
      { type: "AntennaTower", position: [0, 0, 2], params: { color: "#44aaff" } },
    ],
    particles: [{ type: "Bubbles", params: { color: "#88ccff", count: 150, radius: 4 } }],
    lighting: { ambient: "#224488", ambientIntensity: 0.2, sunColor: "#4488ff", sunIntensity: 0.3 },
  },
  "earth-arctic": {
    name: "Arctic Research Station", seed: 302,
    terrain: { type: "icy", roughness: 0.3 },
    atmosphere: { color: "#ddeeff", opacity: 0.08, radius: 7 },
    water: { ice: true },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#ddeeff", glowColor: "#88ccff" } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#88ccff" } },
      { type: "ResearchModule", position: [-1.5, 0, -1.5], params: { color: "#88ccff" } },
      { type: "AntennaTower", position: [0, 0, 2.5], params: { color: "#88ccff" } },
      { type: "IceCutter", position: [2, 0, -1], params: { scale: 1.2 } },
      { type: "PowerCore", position: [-2, 0, 1], params: { color: "#4488ff" } },
    ],
    particles: [{ type: "Snowfall", params: { color: "#ffffff", count: 400, width: 8 } }],
    lighting: { ambient: "#446688", ambientIntensity: 0.3, sunColor: "#88ccff", sunIntensity: 0.3 },
  },
  "earth-stem-alpha": {
    name: "STEM Lab Alpha", seed: 303,
    terrain: { type: "urban", roughness: 0.1 },
    atmosphere: { color: "#44aa88", opacity: 0.08, radius: 7 },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#66ffbb" } },
      { type: "Greenhouse", position: [1.5, 0, 1.5], params: { color: "#66ffbb" } },
      { type: "LandingPad", position: [-1.5, 0, -1.5] },
      { type: "PowerCore", position: [0, 0, -2], params: { color: "#00ff88" } },
      { type: "AntennaTower", position: [0, 0, 2.5], params: { color: "#66ffbb" } },
    ],
    particles: [],
    lighting: { ambient: "#446644", ambientIntensity: 0.4, sunColor: "#88ffbb", sunIntensity: 0.5 },
  },
  "earth-ai-research": {
    name: "AI Research Center", seed: 304,
    terrain: { type: "urban", roughness: 0.1 },
    atmosphere: { color: "#6644aa", opacity: 0.06, radius: 7 },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#9966ff" } },
      { type: "PowerCore", position: [1.5, 0, 1.5], params: { color: "#8844ff" } },
      { type: "CommunicationArray", position: [-1.5, 0, -1.5] },
      { type: "BatteryFarm", position: [2, 0, 0] },
      { type: "AntennaTower", position: [0, 0, 2.5], params: { color: "#9966ff" } },
    ],
    particles: [],
    lighting: { ambient: "#443366", ambientIntensity: 0.3, sunColor: "#9966ff", sunIntensity: 0.4 },
  },
  "earth-launch-complex": {
    name: "Launch Complex 1", seed: 305,
    terrain: { type: "desert", roughness: 0.3 },
    atmosphere: { color: "#778899", opacity: 0.08, radius: 7 },
    structures: [
      { type: "LaunchPad", position: [0, 0, 0], params: { scale: 2 } },
      { type: "FuelDepot", position: [2.5, 0, 0], params: { scale: 1.5 } },
      { type: "FuelDepot", position: [-2.5, 0, 0], params: { scale: 1.5 } },
      { type: "ObservationTower", position: [0, 0, 2.5], params: { color: "#ff6644" } },
      { type: "CommunicationArray", position: [0, 0, -2.5] },
      { type: "CargoContainer", position: [2, 0, 2], params: { color: "#ff6644" } },
    ],
    particles: [],
    lighting: { ambient: "#886644", ambientIntensity: 0.4, sunColor: "#ffaa44", sunIntensity: 0.7 },
  },

/* ═══ MARS (7 procedural) ═══ */
  "mars-colony-central": {
    name: "Mars Colony Central", seed: 401,
    terrain: { type: "desert", roughness: 0.5 },
    atmosphere: { color: "rgba(196,68,46,0.08)", opacity: 0.08, radius: 7 },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#c1442e", glowColor: "#ff8844", radius: 0.5 } },
      { type: "HabitatDome", position: [1.5, 0, 1.5], params: { color: "#c1442e", glowColor: "#ff8844" } },
      { type: "HabitatDome", position: [-1.5, 0, -1.5], params: { color: "#c1442e", glowColor: "#ff8844" } },
      { type: "SolarArray", position: [2.5, 0, 0], params: { panels: 10, span: 1, color: "#1a3a6a" } },
      { type: "Airlock", position: [1, 0, -1], params: { color: "#ff8844" } },
      { type: "AntennaTower", position: [0, 0, 2.5], params: { color: "#ff8844" } },
      { type: "LandingPad", position: [0, 0, -2.5] },
    ],
    particles: [{ type: "DustStorm", params: { color: "#b04428", count: 500, radius: 8 } }],
    lighting: { ambient: "#663322", ambientIntensity: 0.3, sunColor: "#ff8844", sunIntensity: 0.5 },
  },
  "mars-olympus": {
    name: "Olympus Mons Base", seed: 402,
    terrain: { type: "rocky", roughness: 1.5 },
    atmosphere: { color: "rgba(196,68,46,0.06)", opacity: 0.06, radius: 7 },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#ff6644" } },
      { type: "ObservationTower", position: [1.5, 0, 1.5], params: { color: "#ff6644", height: 0.6 } },
      { type: "LandingPad", position: [-1.5, 0, -1.5] },
      { type: "AntennaTower", position: [2, 0, 0], params: { color: "#ff6644" } },
      { type: "PowerCore", position: [0, 0, -2], params: { color: "#ff4400" } },
    ],
    particles: [],
    lighting: { ambient: "#442211", ambientIntensity: 0.2, sunColor: "#ff8844", sunIntensity: 0.4 },
  },
  "mars-valles": {
    name: "Valles Marineris Research", seed: 403,
    terrain: { type: "rocky", roughness: 1.8 },
    structures: [
      { type: "DrillRig", position: [0, 0, 0], params: { scale: 1.2 } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#ffaa44" } },
      { type: "AntennaTower", position: [-1.5, 0, -1.5], params: { color: "#ffaa44" } },
      { type: "CargoContainer", position: [2, 0, -1], params: { color: "#ffaa44" } },
    ],
    particles: [{ type: "DustStorm", params: { color: "#8a3418", count: 400, radius: 7 } }],
    lighting: { ambient: "#553322", ambientIntensity: 0.25, sunColor: "#ffaa44", sunIntensity: 0.5 },
  },
  "mars-north-pole": {
    name: "North Pole Ice Mine", seed: 404,
    terrain: { type: "icy", roughness: 0.3 },
    atmosphere: { color: "#ccddff", opacity: 0.06, radius: 7 },
    water: { ice: true },
    structures: [
      { type: "DrillRig", position: [0, 0, 0], params: { scale: 1.5 } },
      { type: "IceCutter", position: [1.5, 0, 1.5], params: { scale: 1.2 } },
      { type: "HabitatDome", position: [-1.5, 0, -1.5], params: { color: "#ccddff", glowColor: "#88ccff" } },
      { type: "PowerCore", position: [2, 0, 0], params: { color: "#4488ff" } },
      { type: "CargoContainer", position: [-2, 0, 1], params: { color: "#88ccff" } },
    ],
    particles: [{ type: "Snowfall", params: { color: "#ffffff", count: 300, width: 7 } }],
    lighting: { ambient: "#446688", ambientIntensity: 0.3, sunColor: "#88ccff", sunIntensity: 0.3 },
  },
  "mars-phobos": {
    name: "Phobos Station", seed: 405,
    terrain: { type: "rocky", roughness: 0.6 },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#887766", glowColor: "#aaaaaa", radius: 0.5 } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#aaaaaa" } },
      { type: "AntennaTower", position: [-1.5, 0, -1.5], params: { color: "#aaaaaa" } },
      { type: "LandingPad", position: [2.5, 0, 0] },
      { type: "CargoContainer", position: [-2, 0, 1], params: { color: "#aaaaaa" } },
    ],
    particles: [],
    lighting: { ambient: "#444455", ambientIntensity: 0.15, sunColor: "#aaaaaa", sunIntensity: 0.2 },
  },
  "mars-terraform-lab": {
    name: "Terraforming Lab", seed: 406,
    terrain: { type: "desert", roughness: 0.3 },
    atmosphere: { color: "rgba(100,200,100,0.06)", opacity: 0.06, radius: 7 },
    structures: [
      { type: "Greenhouse", position: [0, 0, 0], params: { color: "#88ff44" } },
      { type: "Greenhouse", position: [1.5, 0, 1.5], params: { color: "#88ff44" } },
      { type: "Greenhouse", position: [-1.5, 0, -1.5], params: { color: "#88ff44" } },
      { type: "ResearchModule", position: [0, 0, 2.5], params: { color: "#66aa44" } },
      { type: "WaterTreatment", position: [2, 0, 0] },
    ],
    particles: [{ type: "Bubbles", params: { color: "#88ffaa", count: 100, radius: 3 } }],
    lighting: { ambient: "#446644", ambientIntensity: 0.4, sunColor: "#88ff44", sunIntensity: 0.5 },
  },
  "mars-rover-factory": {
    name: "Rover Factory", seed: 407,
    terrain: { type: "desert", roughness: 0.2 },
    structures: [
      { type: "Refinery", position: [0, 0, 0], params: { scale: 1.5 } },
      { type: "MiningConveyor", position: [1, 0, 1], params: { length: 0.6 } },
      { type: "MiningConveyor", position: [-1, 0, -1], params: { length: 0.6 } },
      { type: "CargoContainer", position: [2, 0, 0], params: { color: "#00aa88" } },
      { type: "CargoContainer", position: [-2, 0, 0], params: { color: "#00aa88" } },
      { type: "LandingPad", position: [0, 0, -2] },
    ],
    particles: [{ type: "DustStorm", params: { color: "#887766", count: 200, radius: 5 } }],
    lighting: { ambient: "#446666", ambientIntensity: 0.3, sunColor: "#00aa88", sunIntensity: 0.5 },
  },
  "mars-launch-complex": {
    name: "Mars Launch Complex", seed: 408,
    terrain: { type: "desert", roughness: 0.2 },
    atmosphere: { color: "rgba(196,68,46,0.06)", opacity: 0.06, radius: 7 },
    structures: [
      { type: "LaunchPad", position: [0, 0, 0], params: { scale: 2 } },
      { type: "FuelDepot", position: [2.5, 0, 0], params: { scale: 1.5 } },
      { type: "FuelDepot", position: [-2.5, 0, 0], params: { scale: 1.5 } },
      { type: "ObservationTower", position: [0, 0, 2.5], params: { color: "#ff6633" } },
      { type: "CommunicationArray", position: [0, 0, -2.5] },
    ],
    particles: [],
    lighting: { ambient: "#664422", ambientIntensity: 0.3, sunColor: "#ff6633", sunIntensity: 0.6 },
  },

/* ═══ ASTEROID BELT (6) ═══ */
  "asteroid-ceres": {
    name: "Ceres Mining Station", seed: 501,
    terrain: { type: "rocky", roughness: 0.8 },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#887766", glowColor: "#88aacc", radius: 0.5 } },
      { type: "DrillRig", position: [2, 0, 0], params: { scale: 1.5 } },
      { type: "DrillRig", position: [-2, 0, 0], params: { scale: 1.5 } },
      { type: "MiningConveyor", position: [1, 0, 1.5], params: { length: 0.6 } },
      { type: "MiningConveyor", position: [-1, 0, -1.5], params: { length: 0.6 } },
      { type: "CargoContainer", position: [0, 0, -2.5], params: { color: "#88aacc" } },
      { type: "PowerCore", position: [0, 0, 2.5], params: { color: "#88aacc" } },
    ],
    particles: [],
    lighting: { ambient: "#445566", ambientIntensity: 0.2, sunColor: "#88aacc", sunIntensity: 0.3 },
  },
  "asteroid-vesta": {
    name: "Vesta Outpost", seed: 502,
    terrain: { type: "rocky", roughness: 1.0 },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#cc8844" } },
      { type: "AntennaTower", position: [1.5, 0, 1.5], params: { color: "#cc8844" } },
      { type: "LandingPad", position: [-1.5, 0, -1.5] },
      { type: "TelescopeArray", position: [0, 0, 0], params: { color: "#cc8844", scale: 0.8 } },
    ],
    particles: [],
    lighting: { ambient: "#554433", ambientIntensity: 0.2, sunColor: "#cc8844", sunIntensity: 0.3 },
  },
  "asteroid-prospector": {
    name: "Asteroid Prospector", seed: 503,
    terrain: { type: "space", roughness: 0.3 },
    structures: [
      { type: "AntennaTower", position: [0, 0, 0], params: { color: "#ffcc00", height: 0.5 } },
      { type: "CommunicationArray", position: [0, 0, 0] },
      { type: "CargoContainer", position: [1.5, 0, 1.5], params: { color: "#ffcc00" } },
      { type: "FuelDepot", position: [-1.5, 0, -1.5] },
    ],
    particles: [],
    lighting: { ambient: "#333344", ambientIntensity: 0.1, sunColor: "#ffcc00", sunIntensity: 0.2 },
  },
  "asteroid-navigation": {
    name: "Belt Navigation Hub", seed: 504,
    terrain: { type: "space", roughness: 0.2 },
    structures: [
      { type: "CommunicationArray", position: [0, 0, 0] },
      { type: "RadarDish", position: [1.5, 0, 1.5], params: { color: "#44aaff" } },
      { type: "RadarDish", position: [-1.5, 0, -1.5], params: { color: "#44aaff" } },
      { type: "ResearchModule", position: [0, 0, 2.5], params: { color: "#44aaff" } },
      { type: "PowerCore", position: [0, 0, -2.5], params: { color: "#44aaff" } },
    ],
    particles: [],
    lighting: { ambient: "#334466", ambientIntensity: 0.15, sunColor: "#44aaff", sunIntensity: 0.2 },
  },
  "asteroid-radar": {
    name: "Deep Space Radar", seed: 505,
    terrain: { type: "space", roughness: 0.2 },
    structures: [
      { type: "RadarDish", position: [0, 0, 0], params: { scale: 2, color: "#00ddff" } },
      { type: "RadarDish", position: [2, 0, 0], params: { color: "#00ddff" } },
      { type: "CommunicationArray", position: [0, 0, 2] },
      { type: "PowerCore", position: [0, 0, -2], params: { color: "#00ddff" } },
    ],
    particles: [],
    lighting: { ambient: "#224466", ambientIntensity: 0.15, sunColor: "#00ddff", sunIntensity: 0.2 },
  },
  "asteroid-psyche": {
    name: "Psyche Mining Colony", seed: 506,
    terrain: { type: "rocky", roughness: 0.7 },
    structures: [
      { type: "Refinery", position: [0, 0, 0], params: { scale: 1.5 } },
      { type: "DrillRig", position: [2, 0, 0], params: { scale: 1.5 } },
      { type: "DrillRig", position: [-2, 0, 0], params: { scale: 1.5 } },
      { type: "MiningConveyor", position: [0, 0, 2], params: { length: 0.8 } },
      { type: "CargoContainer", position: [1.5, 0, -1.5], params: { color: "#ddaa00" } },
      { type: "CargoContainer", position: [-1.5, 0, -1.5], params: { color: "#ddaa00" } },
      { type: "HabitatDome", position: [0, 0, -2.5], params: { color: "#8899aa", glowColor: "#ddaa00" } },
    ],
    particles: [],
    lighting: { ambient: "#554433", ambientIntensity: 0.25, sunColor: "#ddaa00", sunIntensity: 0.3 },
  },

/* ═══ JUPITER (7 procedural) ═══ */
  "jupiter-red-spot": {
    name: "Great Red Spot Observatory", seed: 601,
    terrain: { type: "gaseous", roughness: 0 },
    atmosphere: { color: "#d4a06a", opacity: 0.2, radius: 8 },
    structures: [
      { type: "ObservationTower", position: [0, 0, 0], params: { height: 0.5, color: "#ff6644" } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#ff6644" } },
      { type: "ResearchModule", position: [-1.5, 0, -1.5], params: { color: "#ff6644" } },
      { type: "AntennaTower", position: [0, 0, 2.5], params: { color: "#ff6644" } },
      { type: "LandingPad", position: [0, 0, -2.5] },
    ],
    particles: [{ type: "LightningBolt", params: { color: "#ff6644", height: 1.5 } }],
    lighting: { ambient: "#664422", ambientIntensity: 0.3, sunColor: "#ff6644", sunIntensity: 0.4 },
  },
  "jupiter-io": {
    name: "Io Volcanic Lab", seed: 602,
    terrain: { type: "volcanic", roughness: 1.5 },
    atmosphere: { color: "rgba(204,102,34,0.06)", opacity: 0.06, radius: 7 },
    water: { lava: true },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#ff8844" } },
      { type: "GeothermalVent", position: [1.5, 0, 1.5], params: { color: "#ff4400" } },
      { type: "GeothermalVent", position: [-1.5, 0, -1.5], params: { color: "#ff4400" } },
      { type: "ObservationTower", position: [0, 0, 2], params: { color: "#ff8844" } },
      { type: "PowerCore", position: [0, 0, -2], params: { color: "#ff4400" } },
    ],
    particles: [{ type: "AshFall", params: { color: "#444444", count: 500, width: 7 } }],
    lighting: { ambient: "#442211", ambientIntensity: 0.2, sunColor: "#ff8844", sunIntensity: 0.5 },
  },
  "jupiter-europa": {
    name: "Europa Ice Base", seed: 603,
    terrain: { type: "icy", roughness: 0.4 },
    atmosphere: { color: "rgba(136,170,204,0.08)", opacity: 0.08, radius: 7 },
    water: { ice: true },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#88aacc", glowColor: "#44aaff", radius: 0.5 } },
      { type: "DrillRig", position: [2, 0, 0], params: { scale: 1.2 } },
      { type: "ResearchModule", position: [-2, 0, 0], params: { color: "#44aaff" } },
      { type: "IceCutter", position: [1.5, 0, 1.5], params: { scale: 1.2 } },
      { type: "PowerCore", position: [0, 0, -2.5], params: { color: "#44aaff" } },
      { type: "AntennaTower", position: [0, 0, 2.5], params: { color: "#44aaff" } },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#88ddff", count: 300, radius: 5 } }],
    lighting: { ambient: "#446688", ambientIntensity: 0.2, sunColor: "#44aaff", sunIntensity: 0.3 },
  },
  "jupiter-ganymede": {
    name: "Ganymede Outpost", seed: 604,
    terrain: { type: "rocky", roughness: 0.8 },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#8a9a88", glowColor: "#88ddaa", radius: 0.5 } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#88ddaa" } },
      { type: "AntennaTower", position: [-1.5, 0, -1.5], params: { color: "#88ddaa" } },
      { type: "LandingPad", position: [2.5, 0, 0] },
    ],
    particles: [],
    lighting: { ambient: "#445544", ambientIntensity: 0.2, sunColor: "#88ddaa", sunIntensity: 0.3 },
  },
  "jupiter-callisto": {
    name: "Callisto Research", seed: 605,
    terrain: { type: "rocky", roughness: 1.0 },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#88aa88" } },
      { type: "TelescopeArray", position: [0, 0, 0], params: { color: "#88aa88", scale: 0.8 } },
      { type: "AntennaTower", position: [1.5, 0, 1.5], params: { color: "#88aa88" } },
      { type: "PowerCore", position: [-1.5, 0, -1.5], params: { color: "#88aa88" } },
    ],
    particles: [],
    lighting: { ambient: "#445544", ambientIntensity: 0.15, sunColor: "#88aa88", sunIntensity: 0.2 },
  },
  "jupiter-ring": {
    name: "Jupiter Ring Station", seed: 606,
    terrain: { type: "space", roughness: 0 },
    structures: [
      { type: "HabRing", position: [0, 0, 0], params: { radius: 0.4, scale: 1.5 } },
      { type: "ResearchModule", position: [0, 0, 2], params: { color: "#ffaa44" } },
      { type: "AntennaTower", position: [2, 0, 0], params: { color: "#ffaa44" } },
      { type: "LandingPad", position: [0, 0, -2] },
    ],
    particles: [],
    lighting: { ambient: "#443322", ambientIntensity: 0.15, sunColor: "#ffaa44", sunIntensity: 0.2 },
  },
  "jupiter-atmo-array": {
    name: "Atmospheric Array", seed: 607,
    terrain: { type: "gaseous", roughness: 0 },
    atmosphere: { color: "#d4a06a", opacity: 0.15, radius: 8 },
    structures: [
      { type: "AntennaTower", position: [0, 0, 0], params: { color: "#ffaa44", height: 0.6 } },
      { type: "AntennaTower", position: [2, 0, 0], params: { color: "#ffaa44" } },
      { type: "AntennaTower", position: [-2, 0, 0], params: { color: "#ffaa44" } },
      { type: "AntennaTower", position: [0, 0, 2], params: { color: "#ffaa44" } },
      { type: "ResearchModule", position: [0, 0, -2], params: { color: "#ffaa44" } },
    ],
    particles: [{ type: "LightningBolt", params: { color: "#ffaa44", height: 2 } }],
    lighting: { ambient: "#553322", ambientIntensity: 0.25, sunColor: "#ffaa44", sunIntensity: 0.3 },
  },
  "jupiter-magnetosphere": {
    name: "Magnetosphere Lab", seed: 608,
    terrain: { type: "space", roughness: 0 },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#44aaff" } },
      { type: "CommunicationArray", position: [0, 0, 0] },
      { type: "PowerCore", position: [1.5, 0, 1.5], params: { color: "#44aaff" } },
      { type: "AntennaTower", position: [-1.5, 0, -1.5], params: { color: "#44aaff" } },
    ],
    particles: [{ type: "Aurora", params: { color: "#44ff88", width: 8 } }],
    lighting: { ambient: "#224466", ambientIntensity: 0.15, sunColor: "#44aaff", sunIntensity: 0.2 },
  },

/* ═══ SATURN (6) ═══ */
  "saturn-titan": {
    name: "Titan Hydrocarbon Lab", seed: 701,
    terrain: { type: "rocky", roughness: 0.8 },
    atmosphere: { color: "rgba(200,136,50,0.15)", opacity: 0.15, radius: 8 },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#b87828", glowColor: "#ffaa44", radius: 0.5 } },
      { type: "ResearchModule", position: [2, 0, 0], params: { color: "#ffaa44" } },
      { type: "ResearchModule", position: [-2, 0, 0], params: { color: "#ffaa44" } },
      { type: "FuelDepot", position: [1.5, 0, 1.5], params: { scale: 1.2 } },
      { type: "AntennaTower", position: [0, 0, 2.5], params: { color: "#ffaa44" } },
      { type: "LandingPad", position: [0, 0, -2.5] },
    ],
    particles: [{ type: "Bubbles", params: { color: "#ffaa44", count: 150, radius: 4 } }],
    lighting: { ambient: "#664422", ambientIntensity: 0.3, sunColor: "#ffaa44", sunIntensity: 0.3 },
  },
  "saturn-enceladus": {
    name: "Enceladus Ice Base", seed: 702,
    terrain: { type: "icy", roughness: 0.5 },
    atmosphere: { color: "rgba(200,230,240,0.06)", opacity: 0.06, radius: 7 },
    water: { ice: true },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#cceeef", glowColor: "#88ccff", radius: 0.5 } },
      { type: "DrillRig", position: [2, 0, 0], params: { scale: 1.2 } },
      { type: "ResearchModule", position: [-2, 0, 0], params: { color: "#88ccff" } },
      { type: "IceCutter", position: [1.5, 0, 1.5], params: { scale: 1.5 } },
      { type: "GeothermalVent", position: [-1.5, 0, -1.5], params: { color: "#88ccff" } },
      { type: "AntennaTower", position: [0, 0, 2.5], params: { color: "#88ccff" } },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#88ddff", count: 400, radius: 6 } }],
    lighting: { ambient: "#446688", ambientIntensity: 0.2, sunColor: "#88ccff", sunIntensity: 0.3 },
  },
  "saturn-mimas": {
    name: "Mimas Impact Study", seed: 703,
    terrain: { type: "rocky", roughness: 1.5 },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#aabbcc" } },
      { type: "DrillRig", position: [1.5, 0, 1.5], params: { scale: 1.2 } },
      { type: "AntennaTower", position: [-1.5, 0, -1.5], params: { color: "#aabbcc" } },
    ],
    particles: [],
    lighting: { ambient: "#445566", ambientIntensity: 0.15, sunColor: "#aabbcc", sunIntensity: 0.2 },
  },
  "saturn-dione": {
    name: "Dione Observation Deck", seed: 704,
    terrain: { type: "rocky", roughness: 0.5 },
    structures: [
      { type: "ObservationTower", position: [0, 0, 0], params: { height: 0.6, color: "#8899bb" } },
      { type: "TelescopeArray", position: [0, 0, 0], params: { color: "#8899bb", scale: 0.8 } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#8899bb" } },
      { type: "LandingPad", position: [-1.5, 0, -1.5] },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#88bbdd", count: 200, radius: 4 } }],
    lighting: { ambient: "#445566", ambientIntensity: 0.2, sunColor: "#8899bb", sunIntensity: 0.3 },
  },
  "saturn-rhea": {
    name: "Rhea Cryo Facility", seed: 705,
    terrain: { type: "rocky", roughness: 0.5 },
    structures: [
      { type: "CryoTank", position: [0, 0, 0], params: { scale: 1.2, color: "#99aabb" } },
      { type: "CryoTank", position: [1.5, 0, 1.5], params: { color: "#99aabb" } },
      { type: "CryoTank", position: [-1.5, 0, -1.5], params: { color: "#99aabb" } },
      { type: "ResearchModule", position: [0, 0, 2.5], params: { color: "#99aabb" } },
      { type: "PowerCore", position: [0, 0, -2.5], params: { color: "#99aabb" } },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#88bbdd", count: 200, radius: 4 } }],
    lighting: { ambient: "#445566", ambientIntensity: 0.15, sunColor: "#99aabb", sunIntensity: 0.2 },
  },
  "saturn-ring-hub": {
    name: "Saturn Ring Hub", seed: 706,
    terrain: { type: "space", roughness: 0 },
    structures: [
      { type: "HabRing", position: [0, 0, 0], params: { radius: 0.5, scale: 1.5 } },
      { type: "ResearchModule", position: [2, 0, 0], params: { color: "#d4c090" } },
      { type: "ResearchModule", position: [-2, 0, 0], params: { color: "#d4c090" } },
      { type: "AntennaTower", position: [0, 0, 2], params: { color: "#d4c090" } },
      { type: "LandingPad", position: [0, 0, -2] },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#d4c090", count: 300, radius: 6 } }],
    lighting: { ambient: "#554433", ambientIntensity: 0.15, sunColor: "#d4c090", sunIntensity: 0.2 },
  },

/* ═══ URANUS (4) ═══ */
  "uranus-ring-station": {
    name: "Ring Station Alpha", seed: 801,
    terrain: { type: "space", roughness: 0 },
    atmosphere: { color: "rgba(126,200,227,0.12)", opacity: 0.12, radius: 8 },
    structures: [
      { type: "HabRing", position: [0, 0, 0], params: { radius: 0.4, scale: 1.5 } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#88ccee" } },
      { type: "ResearchModule", position: [-1.5, 0, -1.5], params: { color: "#88ccee" } },
      { type: "CommunicationArray", position: [0, 0, 2] },
      { type: "LandingPad", position: [0, 0, -2] },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#88ccee", count: 200, radius: 5 } }],
    lighting: { ambient: "#446688", ambientIntensity: 0.2, sunColor: "#88ccee", sunIntensity: 0.2 },
  },
  "uranus-miranda": {
    name: "Miranda Research Lab", seed: 802,
    terrain: { type: "rocky", roughness: 1.2 },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#aabbcc" } },
      { type: "TelescopeArray", position: [0, 0, 0], params: { color: "#aabbcc", scale: 0.8 } },
      { type: "ObservationTower", position: [1.5, 0, 1.5], params: { color: "#aabbcc" } },
      { type: "AntennaTower", position: [-1.5, 0, -1.5], params: { color: "#aabbcc" } },
    ],
    particles: [],
    lighting: { ambient: "#445566", ambientIntensity: 0.15, sunColor: "#aabbcc", sunIntensity: 0.2 },
  },
  "uranus-ariel": {
    name: "Ariel Ice Base", seed: 803,
    terrain: { type: "rocky", roughness: 0.8 },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#ccddee", glowColor: "#aaccdd", radius: 0.5 } },
      { type: "IceCutter", position: [1.5, 0, 1.5], params: { scale: 1.2 } },
      { type: "AntennaTower", position: [-1.5, 0, -1.5], params: { color: "#aaccdd" } },
      { type: "LandingPad", position: [2.5, 0, 0] },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#aaccdd", count: 200, radius: 4 } }],
    lighting: { ambient: "#445566", ambientIntensity: 0.2, sunColor: "#aaccdd", sunIntensity: 0.2 },
  },
  "uranus-oberon": {
    name: "Oberon Observatory", seed: 804,
    terrain: { type: "rocky", roughness: 0.6 },
    structures: [
      { type: "ObservationTower", position: [0, 0, 0], params: { height: 0.6, color: "#8899bb" } },
      { type: "TelescopeArray", position: [0, 0, 0], params: { color: "#8899bb", scale: 1.2 } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#8899bb" } },
      { type: "PowerCore", position: [-1.5, 0, -1.5], params: { color: "#8899bb" } },
      { type: "AntennaTower", position: [0, 0, 2.5], params: { color: "#8899bb" } },
    ],
    particles: [],
    lighting: { ambient: "#445566", ambientIntensity: 0.15, sunColor: "#8899bb", sunIntensity: 0.2 },
  },

/* ═══ NEPTUNE (4) ═══ */
  "neptune-triton": {
    name: "Triton Geyser Station", seed: 901,
    terrain: { type: "icy", roughness: 0.6 },
    atmosphere: { color: "rgba(68,102,170,0.08)", opacity: 0.08, radius: 7 },
    water: { ice: true },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#4466aa", glowColor: "#88aaff", radius: 0.5 } },
      { type: "GeothermalVent", position: [1.5, 0, 1.5], params: { color: "#88aaff" } },
      { type: "GeothermalVent", position: [-1.5, 0, -1.5], params: { color: "#88aaff" } },
      { type: "ResearchModule", position: [0, 0, 2.5], params: { color: "#88aaff" } },
      { type: "AntennaTower", position: [0, 0, -2.5], params: { color: "#88aaff" } },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#88aaff", count: 300, radius: 5 } }],
    lighting: { ambient: "#334466", ambientIntensity: 0.2, sunColor: "#88aaff", sunIntensity: 0.2 },
  },
  "neptune-nereid": {
    name: "Nereid Outpost", seed: 902,
    terrain: { type: "rocky", roughness: 0.6 },
    structures: [
      { type: "ResearchModule", position: [0, 0, 0], params: { color: "#6699cc" } },
      { type: "AntennaTower", position: [1.5, 0, 1.5], params: { color: "#6699cc" } },
      { type: "TelescopeArray", position: [0, 0, 0], params: { color: "#6699cc", scale: 0.8 } },
      { type: "PowerCore", position: [-1.5, 0, -1.5], params: { color: "#6699cc" } },
    ],
    particles: [],
    lighting: { ambient: "#334466", ambientIntensity: 0.15, sunColor: "#6699cc", sunIntensity: 0.2 },
  },
  "neptune-storm-watch": {
    name: "Storm Watch Platform", seed: 903,
    terrain: { type: "gaseous", roughness: 0 },
    atmosphere: { color: "#3355aa", opacity: 0.15, radius: 8 },
    structures: [
      { type: "ObservationTower", position: [0, 0, 0], params: { height: 0.6, color: "#4466cc" } },
      { type: "AntennaTower", position: [2, 0, 0], params: { color: "#4466cc" } },
      { type: "AntennaTower", position: [-2, 0, 0], params: { color: "#4466cc" } },
      { type: "ResearchModule", position: [0, 0, 2], params: { color: "#4466cc" } },
      { type: "LandingPad", position: [0, 0, -2] },
    ],
    particles: [{ type: "LightningBolt", params: { color: "#4466cc", height: 2 } }],
    lighting: { ambient: "#224466", ambientIntensity: 0.2, sunColor: "#4466cc", sunIntensity: 0.2 },
  },
  "neptune-kuiper": {
    name: "Kuiper Belt Launch", seed: 904,
    terrain: { type: "space", roughness: 0 },
    structures: [
      { type: "LaunchPad", position: [0, 0, 0], params: { scale: 1.5 } },
      { type: "FuelDepot", position: [2, 0, 0], params: { scale: 1.5 } },
      { type: "FuelDepot", position: [-2, 0, 0], params: { scale: 1.5 } },
      { type: "CommunicationArray", position: [0, 0, 2] },
      { type: "ObservationTower", position: [0, 0, -2.5], params: { color: "#5577cc" } },
    ],
    particles: [],
    lighting: { ambient: "#334466", ambientIntensity: 0.1, sunColor: "#5577cc", sunIntensity: 0.15 },
  },

/* ═══ DEEP SPACE (4) ═══ */
  "deep-pluto": {
    name: "Pluto Research Base", seed: 1001,
    terrain: { type: "rocky", roughness: 1.0 },
    atmosphere: { color: "rgba(136,122,104,0.04)", opacity: 0.04, radius: 7 },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#887766", glowColor: "#88aacc", radius: 0.5 } },
      { type: "ResearchModule", position: [2, 0, 0], params: { color: "#88aacc" } },
      { type: "AntennaTower", position: [-2, 0, 0], params: { color: "#88aacc" } },
      { type: "LandingPad", position: [0, 0, -2.5] },
      { type: "PowerCore", position: [0, 0, 2.5], params: { color: "#88aacc" } },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#88aacc", count: 200, radius: 4 } }],
    lighting: { ambient: "#445566", ambientIntensity: 0.1, sunColor: "#88aacc", sunIntensity: 0.15 },
  },
  "deep-charon": {
    name: "Charon Observatory", seed: 1002,
    terrain: { type: "rocky", roughness: 0.6 },
    structures: [
      { type: "ObservationTower", position: [0, 0, 0], params: { height: 0.6, color: "#99aabb" } },
      { type: "TelescopeArray", position: [0, 0, 0], params: { color: "#99aabb", scale: 1.2 } },
      { type: "ResearchModule", position: [1.5, 0, 1.5], params: { color: "#99aabb" } },
      { type: "PowerCore", position: [-1.5, 0, -1.5], params: { color: "#99aabb" } },
    ],
    particles: [],
    lighting: { ambient: "#445566", ambientIntensity: 0.1, sunColor: "#99aabb", sunIntensity: 0.15 },
  },
  "deep-oort": {
    name: "Oort Cloud Station", seed: 1003,
    terrain: { type: "space", roughness: 0.3 },
    structures: [
      { type: "HabitatDome", position: [0, 0, 0], params: { color: "#334455", glowColor: "#557788", radius: 0.5 } },
      { type: "CommunicationArray", position: [0, 0, 0] },
      { type: "AntennaTower", position: [1.5, 0, 1.5], params: { color: "#557788" } },
      { type: "LandingPad", position: [-1.5, 0, -1.5] },
      { type: "ObservationTower", position: [0, 0, 2], params: { color: "#557788" } },
    ],
    particles: [{ type: "IceCrystals", params: { color: "#557788", count: 300, radius: 6 } }],
    lighting: { ambient: "#334455", ambientIntensity: 0.08, sunColor: "#557788", sunIntensity: 0.1 },
  },
  "deep-interstellar": {
    name: "Interstellar Probe", seed: 1004,
    terrain: { type: "space", roughness: 0.1 },
    structures: [
      { type: "CommunicationArray", position: [0, 0, 0] },
      { type: "AntennaTower", position: [0, 0, 1.5], params: { color: "#00d4ff", height: 0.6 } },
      { type: "PowerCore", position: [1.5, 0, 0], params: { color: "#00d4ff" } },
      { type: "BatteryFarm", position: [-1.5, 0, 0] },
    ],
    particles: [{ type: "Aurora", params: { color: "#00d4ff", width: 6 } }],
    lighting: { ambient: "#223344", ambientIntensity: 0.08, sunColor: "#00d4ff", sunIntensity: 0.1 },
  },
};

export function getWorldConfig(id: string): WorldConfig | undefined {
  return WORLD_CONFIGS[id];
}